# Generated by Django 5.2.7 on 2026-04-02 04:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('salary', 'Salary'), ('investment', 'Investment'), ('bonus', 'Bonus'), ('food', 'Food'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='users.user')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='records_fin_user_id_ca1565_idx'), models.Index(fields=['user', 'transaction_type'], name='records_fin_user_id_2d6ae3_idx'), models.Index(fields=['user', 'category'], name='records_fin_user_id_fff57e_idx'), models.Index(fields=['is_deleted'], name='records_fin_is_dele_615775_idx')],
            },
        ),
    ]
